name: Service Status Check

on:
  schedule:
  - cron: "*/13 * * * *"
  
# æ·»åŠ æ‰‹åŠ¨è§¦å‘äº‹ä»¶
  workflow_dispatch:
    inputs:
      manualReason:
        description: 'Input description'
        required: false
        default: 'æ‰‹åŠ¨è§¦å‘æµ‹è¯•'

jobs:
  service-check:
    runs-on: ubuntu-latest 
    timeout-minutes: 3
    name: Check knloop service status
    env:
      WEBHOOK_KEY: ${{ secrets.WECHAT_WEBHOOK_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # æ–°ä»»åŠ¡æŒ‚èµ·
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Shell Script
        id: shell_script_run
        run: |
          chmod +x ./checkshell/servicecheck.sh
          bash ./checkshell/servicecheck.sh

      # - name: Commit and push changes
      #   run: |
      #     git config --local user.name 'Github Actions'
      #     git config --local user.email 'Actions@knloop.com'
      #     git add -A --force ./logs/
      #     git commit -m 'ğŸ†™ [Automated] Update service status logs'
      #     git push origin main
